// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlcvzzkqtuehtjronnoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsY3Z6emtxdHVlaHRqcm9ubm9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NDg2NzMsImV4cCI6MjA2OTAyNDY3M30.P6hm67m_uCOSsYi5Zjyf7Sjj9C-yjwCZJubdFj0GyXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});